### ISSUE TITLE
Reset:How i can reset the value after selecting some value in SelectedFormField?

### ISSUE THREAD

**Issue by expertdev-designer** [m3uzz/select_form_field#11]
Reset:How i can reset the value after selecting some value in SelectedFormField

Please help

**Comment by hslbetto** [comment]
You need to use controller and when you need, just call the method clean from controller.

TextEditingController? _controller;

...

SelectFormField(
                type: SelectFormFieldType.dialog,
                controller: _controller,
...
);

...

ElevatedButton(
                onPressed: () {
                  final loForm = _oFormKey.currentState;
                  loForm?.reset();

                  setState(() {
                    _valueChanged = '';
                    _valueToValidate = '';
                    _valueSaved = '';
                    _controller?.clear();
                  });
                },
                child: Text('Reset'),
              ),
