### ISSUE TITLE
Unhandled Exception: type 'Null' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by jackiepapers** [m3uzz/select_form_field#4]
If I click outside of the dropdown instead of selecting an item this error is returned:
`[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: type 'Null' is not a subtype of type 'String'
#0      _SelectFormFieldState._showSelectFormFieldMenu (package:select_form_field/select_form_field.dart:516:12)
<asynchronous suspension>`

**Comment by papakay** [comment]
I have similar error too! Please can you kindly provide a solution to this.

**Comment by papakay** [comment]
Hi @jackiepapers, please have you found a work around to this?

**Comment by jackiepapers** [comment]
No, I haven’t. It seems to be more of a warning and isn’t actually affecting my app so I just ignore it. Would be nice to not have to see it though.

**Comment by papakay** [comment]
In my own case it causes the app to freeze and I have to restart the app. I'm using Flutter 2.0.5

**Comment by jackiepapers** [comment]
Maybe just make your own Flutter DropdownButton. It doesn’t seem to have this issue.

**Comment by cjcv123** [comment]
anyone solved this problem?

**Comment by jackiepapers** [comment]
I added this line `if (lvPicked == null) return;` in the `select_form_field/select_form_field.dart` file after line 516 code block.
