### ISSUE TITLE
Expected a value of type '(() => Map<String, String>)?', but got one of type '() => Map<String, dynamic>'

### ISSUE THREAD

**Issue by HevelMc** [m3uzz/select_form_field#8]
This error occurs since the last commit, probably because of the firstWhere() line 431 (although I don't know why).

I haven't found any way to fix this bug except replacing the firstWhere with something else (forEach + return when the condition is  valid)
I put my solution in a pull request if you want to accept it.

**Comment by hslbetto** [comment]
Hi @HevelMc, can you show me the use case and the error returned? 
Your solution are a different way to do the same thing.

**Comment by HevelMc** [comment]
Hello, sorry it took me a while to reply, but I finally understood why the error appeared (well more or less understood).

This code returns the error indicated above:
```dart
List<String> companyListDropdown = [
    "Andralude",
    "Orange",
    "SupOptique",
    "Thales"
];
return SelectFormField(
    onChanged: print,
    initialValue: "Toutes",
    labelText: "Entreprise",
    items: companyListDropdown
        .map((e) => {"value": e})
        .toList(),
),
```

But if I modify the line with map function to:
```dart
.map((e) => {"value": e as dynamic})
```
The problem is fixed.

I think that the problem comes from the way firstWhere works, because with the forEach (#9) the problem does not appear.

**Comment by hslbetto** [comment]
Check version 2.2.0
